#!/usr/bin/env python

# classes for each steps
class CreateFormatReferenceParams():
    scripts_dir = ''
    reference_dir = ''
    email = ''
    picard = ''
    partition = ''
    dictionary_out = ''
    regex = '.fa'
    fp = 'config'
    dictionary = '.dict'

class CreateAlignmentParams():
    bwa = ''
    email = ''
    sleep = ''
    partition = ''
    cpu_fqsam = ''
    input_dir = ''
    output_dir = ''
    scripts_dir = ''
    analysis_dir = ''
    reference_dir = ''
    fp = 'config'

class CreateQualityParams():
    input_dir = ''
    output_dir = ''
    qcheck_dir = ''
    fp = 'config'

class CreateControlQualityParams():
    email = ''
    sleep = ''
    fastqc = ''
    partition = ''
    cpu_fastq = ''
    input_dir = ''
    output_dir = ''
    scripts_dir = ''
    analysis_dir = ''
    fp = 'config'

class CreateBAMProcessingParams():
    jvm = ''
    gatk = ''
    email = ''
    picard = ''
    partition = ''
    cpu_sambam = ''
    tmp_dir = ''
    input_dir = ''
    output_dir = ''
    scripts_dir = ''
    analysis_dir = ''
    software_dir = ''
    reference_dir = ''
    fp = 'config'

class CreateMergeBAMParams():
    email = ''
    sleep = ''
    bamutil = ''
    samtools = ''
    partition = ''
    cpu_mergebam = ''
    input_dir = ''
    output_dir = ''
    scripts_dir = ''
    analysis_dir = ''
    reference_dir = ''
    fp = 'config'

class CreateVariantCallingParams():
    gatk = ''
    bgzip = ''
    email = ''
    sleep = ''
    tabix = ''
    htslib = ''
    samtools = ''
    partition = ''
    cpu_bamvcf = ''
    tmp_dir = ''
    input_dir = ''
    output_dir = ''
    scripts_dir = ''
    analysis_dir = ''
    software_dir = ''
    reference_dir = ''
    fp = 'config'
